// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: api/proto/rank.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankService_UpdateScore_FullMethodName = "/corerank.v1.RankService/UpdateScore"
	RankService_GetTopRank_FullMethodName  = "/corerank.v1.RankService/GetTopRank"
)

// RankServiceClient is the client API for RankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================================
// RankService 核心服务定义
//
// 提供分数更新和排行榜查询两大核心功能。
// 在高并发场景下，这两个操作的性能直接影响玩家体验。
// ============================================================================
type RankServiceClient interface {
	// UpdateScore 更新玩家分数
	//
	// 游戏结束后调用，更新玩家的排行榜分数。
	// 内部使用 Redis ZADD 命令，并采用复合分数算法解决同分排序问题。
	//
	// 性能要求：P99 延迟 < 10ms
	UpdateScore(ctx context.Context, in *UpdateScoreRequest, opts ...grpc.CallOption) (*UpdateScoreResponse, error)
	// GetTopRank 获取排行榜
	//
	// 支持获取 Top N 排名和分页查询。
	// 内部使用 Redis ZREVRANGE 命令，复杂度 O(log N + M)。
	//
	// 性能要求：P99 延迟 < 50ms（Top 100 场景）
	GetTopRank(ctx context.Context, in *GetTopRankRequest, opts ...grpc.CallOption) (*GetTopRankResponse, error)
}

type rankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankServiceClient(cc grpc.ClientConnInterface) RankServiceClient {
	return &rankServiceClient{cc}
}

func (c *rankServiceClient) UpdateScore(ctx context.Context, in *UpdateScoreRequest, opts ...grpc.CallOption) (*UpdateScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScoreResponse)
	err := c.cc.Invoke(ctx, RankService_UpdateScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) GetTopRank(ctx context.Context, in *GetTopRankRequest, opts ...grpc.CallOption) (*GetTopRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopRankResponse)
	err := c.cc.Invoke(ctx, RankService_GetTopRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServiceServer is the server API for RankService service.
// All implementations must embed UnimplementedRankServiceServer
// for forward compatibility.
//
// ============================================================================
// RankService 核心服务定义
//
// 提供分数更新和排行榜查询两大核心功能。
// 在高并发场景下，这两个操作的性能直接影响玩家体验。
// ============================================================================
type RankServiceServer interface {
	// UpdateScore 更新玩家分数
	//
	// 游戏结束后调用，更新玩家的排行榜分数。
	// 内部使用 Redis ZADD 命令，并采用复合分数算法解决同分排序问题。
	//
	// 性能要求：P99 延迟 < 10ms
	UpdateScore(context.Context, *UpdateScoreRequest) (*UpdateScoreResponse, error)
	// GetTopRank 获取排行榜
	//
	// 支持获取 Top N 排名和分页查询。
	// 内部使用 Redis ZREVRANGE 命令，复杂度 O(log N + M)。
	//
	// 性能要求：P99 延迟 < 50ms（Top 100 场景）
	GetTopRank(context.Context, *GetTopRankRequest) (*GetTopRankResponse, error)
	mustEmbedUnimplementedRankServiceServer()
}

// UnimplementedRankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankServiceServer struct{}

func (UnimplementedRankServiceServer) UpdateScore(context.Context, *UpdateScoreRequest) (*UpdateScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScore not implemented")
}
func (UnimplementedRankServiceServer) GetTopRank(context.Context, *GetTopRankRequest) (*GetTopRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopRank not implemented")
}
func (UnimplementedRankServiceServer) mustEmbedUnimplementedRankServiceServer() {}
func (UnimplementedRankServiceServer) testEmbeddedByValue()                     {}

// UnsafeRankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServiceServer will
// result in compilation errors.
type UnsafeRankServiceServer interface {
	mustEmbedUnimplementedRankServiceServer()
}

func RegisterRankServiceServer(s grpc.ServiceRegistrar, srv RankServiceServer) {
	// If the following call pancis, it indicates UnimplementedRankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankService_ServiceDesc, srv)
}

func _RankService_UpdateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).UpdateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_UpdateScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).UpdateScore(ctx, req.(*UpdateScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_GetTopRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).GetTopRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_GetTopRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).GetTopRank(ctx, req.(*GetTopRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankService_ServiceDesc is the grpc.ServiceDesc for RankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corerank.v1.RankService",
	HandlerType: (*RankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateScore",
			Handler:    _RankService_UpdateScore_Handler,
		},
		{
			MethodName: "GetTopRank",
			Handler:    _RankService_GetTopRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/rank.proto",
}

const (
	MatchService_CreateMatchTicket_FullMethodName = "/corerank.v1.MatchService/CreateMatchTicket"
	MatchService_GetMatchTicket_FullMethodName    = "/corerank.v1.MatchService/GetMatchTicket"
	MatchService_CancelMatchTicket_FullMethodName = "/corerank.v1.MatchService/CancelMatchTicket"
	MatchService_GetMatchResult_FullMethodName    = "/corerank.v1.MatchService/GetMatchResult"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchService 提供匹配票据生命周期接口。
type MatchServiceClient interface {
	CreateMatchTicket(ctx context.Context, in *CreateMatchTicketRequest, opts ...grpc.CallOption) (*CreateMatchTicketResponse, error)
	GetMatchTicket(ctx context.Context, in *GetMatchTicketRequest, opts ...grpc.CallOption) (*GetMatchTicketResponse, error)
	CancelMatchTicket(ctx context.Context, in *CancelMatchTicketRequest, opts ...grpc.CallOption) (*CancelMatchTicketResponse, error)
	GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...grpc.CallOption) (*GetMatchResultResponse, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) CreateMatchTicket(ctx context.Context, in *CreateMatchTicketRequest, opts ...grpc.CallOption) (*CreateMatchTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMatchTicketResponse)
	err := c.cc.Invoke(ctx, MatchService_CreateMatchTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatchTicket(ctx context.Context, in *GetMatchTicketRequest, opts ...grpc.CallOption) (*GetMatchTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchTicketResponse)
	err := c.cc.Invoke(ctx, MatchService_GetMatchTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) CancelMatchTicket(ctx context.Context, in *CancelMatchTicketRequest, opts ...grpc.CallOption) (*CancelMatchTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMatchTicketResponse)
	err := c.cc.Invoke(ctx, MatchService_CancelMatchTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...grpc.CallOption) (*GetMatchResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchResultResponse)
	err := c.cc.Invoke(ctx, MatchService_GetMatchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility.
//
// MatchService 提供匹配票据生命周期接口。
type MatchServiceServer interface {
	CreateMatchTicket(context.Context, *CreateMatchTicketRequest) (*CreateMatchTicketResponse, error)
	GetMatchTicket(context.Context, *GetMatchTicketRequest) (*GetMatchTicketResponse, error)
	CancelMatchTicket(context.Context, *CancelMatchTicketRequest) (*CancelMatchTicketResponse, error)
	GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultResponse, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchServiceServer struct{}

func (UnimplementedMatchServiceServer) CreateMatchTicket(context.Context, *CreateMatchTicketRequest) (*CreateMatchTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMatchTicket not implemented")
}
func (UnimplementedMatchServiceServer) GetMatchTicket(context.Context, *GetMatchTicketRequest) (*GetMatchTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchTicket not implemented")
}
func (UnimplementedMatchServiceServer) CancelMatchTicket(context.Context, *CancelMatchTicketRequest) (*CancelMatchTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMatchTicket not implemented")
}
func (UnimplementedMatchServiceServer) GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchResult not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}
func (UnimplementedMatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_CreateMatchTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).CreateMatchTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_CreateMatchTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).CreateMatchTicket(ctx, req.(*CreateMatchTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatchTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatchTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetMatchTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatchTicket(ctx, req.(*GetMatchTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_CancelMatchTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).CancelMatchTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_CancelMatchTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).CancelMatchTicket(ctx, req.(*CancelMatchTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetMatchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatchResult(ctx, req.(*GetMatchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corerank.v1.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatchTicket",
			Handler:    _MatchService_CreateMatchTicket_Handler,
		},
		{
			MethodName: "GetMatchTicket",
			Handler:    _MatchService_GetMatchTicket_Handler,
		},
		{
			MethodName: "CancelMatchTicket",
			Handler:    _MatchService_CancelMatchTicket_Handler,
		},
		{
			MethodName: "GetMatchResult",
			Handler:    _MatchService_GetMatchResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/rank.proto",
}
